name: Generate Sankey Diagram

on:
  workflow_run:
    workflows: ["Run Enrichment Process"]
    types:
      - completed
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *" # Daily at 4pm UTC, after the CVSS-BT data update

permissions:
  contents: write

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r code/requirements.txt

    - name: Generate Sankey Diagram
      run: |
        python code/generate_sankey.py

    - name: Configure git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: Commit and push if there are changes
      run: |
        git add CVSS-BT-Enrichment.png
        git diff --staged --quiet || git commit -m "Update Sankey diagram [skip ci]"
        git push origin main || echo "No changes to push"
